## Importing and Exporting arrays

In [1]:
# save an array to file
import numpy as np

In [2]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# save to text
np.savetxt("test_matrix.txt", x)

In [4]:
!ls -a

.   data		numpy-01.ipynb	numpy-03.ipynb
..  .ipynb_checkpoints	numpy-02.ipynb	test_matrix.txt


In [5]:
!cat test_matrix.txt

1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00
7.000000000000000000e+00 8.000000000000000000e+00 9.000000000000000000e+00


In [13]:
np.savetxt("test_matrix2.txt", x, \
            fmt="%2.3f", delimiter=",", \
            header='this is a header', \
            footer='this is a footer', \
            comments='## ' 
       )

In [14]:
!cat test_matrix2.txt

## this is a header
1.000,2.000,3.000
4.000,5.000,6.000
7.000,8.000,9.000
## this is a footer


In [15]:
np.save("x_mat.npy", x)

In [16]:
!cat x_mat.npy

�NUMPYF{'descr': '<i8', 'fortran_order': False, 'shape': (3, 3), }          
	

## Import array

In [18]:
np.genfromtxt('test_matrix2.txt', delimiter="," \
             )

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [27]:
np.genfromtxt('test_matrix2.txt', delimiter=",", 
              skip_header=2, skip_footer=1, 
              usecols=(0,-1)
             )

array([ 4.,  6.])

## Importing Weather Data

In [28]:
!head -2 data/zrh_weather.txt

"Date"&"CEST"&"Max_TemperatureC"&"Mean_TemperatureC"&"Min_TemperatureC"&"Dew_PointC"&"MeanDew_PointC"&"Min_DewpointC"&"Max_Humidity"&"Mean_Humidity"&"Min_Humidity"&"Max_Sea_Level_PressurehPa"&"Mean_Sea_Level_PressurehPa"&"Min_Sea_Level_PressurehPa"&"Max_VisibilityKm"&"Mean_VisibilityKm"&"Min_VisibilitykM"&"Max_Wind_SpeedKm_h"&"Mean_Wind_SpeedKm_h"&"Max_Gust_SpeedKm_h"&"Precipitationmm"&"CloudCover"&"Events"&"WindDirDegrees"
"1"&2017-07-01&"2017-7-1"&21&17&13&12&9&8&88&62&34&1019&1015&1011&31&11&10&27&14&45&0.25&5&"Rain"&252


In [29]:
weather = np.genfromtxt('data/zrh_weather.txt',
                       delimiter = '&',
                       skip_header = 1,
                       usecols=(3,4,5))

In [30]:
weather[0:3,:]

array([[ 21.,  17.,  13.],
       [ 18.,  15.,  12.],
       [ 24.,  19.,  14.]])

In [31]:
from datetime import datetime

str2date = lambda x: datetime.strptime(x.decode("utf-8"), '%Y-%m-%d')


dates = np.genfromtxt('data/zrh_weather.txt', delimiter='&',
                      skip_header=1, usecols=(1),
                     dtype='object').astype(str)

In [33]:
dates[:3]

array(['2017-07-01', '2017-07-02', '2017-07-03'],
      dtype='<U10')

## Summarizing data

In [49]:
# what was the max temp in zurich
np.max(weather[:,0:1], axis=)

34.0

In [56]:
np.argmax(weather[:,0],axis=0)

5

In [58]:
dates[np.argmax(weather[:,0],axis=0)]

'2017-07-06'

In [60]:
np.unique(weather[:,0], return_counts=True)

(array([ 13.,  14.,  18.,  19.,  20.,  21.,  22.,  24.,  25.,  26.,  27.,
         28.,  29.,  30.,  31.,  32.,  34.]),
 array([1, 1, 2, 1, 1, 6, 5, 7, 1, 3, 5, 6, 3, 1, 3, 3, 2]))

In [61]:
minnp.min(weather[:,2])

9.0

In [64]:
mindate = np.argmin(weather[:,2])

In [65]:
dates[mindate]

'2017-07-04'

In [66]:
np.unique(weather[:,2], return_counts=True)

(array([  9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]),
 array([ 1,  3,  7,  8,  4, 10,  8,  5,  2,  2,  1]))

In [74]:
max_temp = np.max(weather[:,0])
min_temp = np.min(weather[:,2])
extremes = np.array([max_temp, min_temp])
print(extremes)

[ 34.   9.]


In [79]:
np.savetxt('extremes.txt',
           extremes,
           header = 'Temperature Extremes',
           fmt = '%2.2f')

In [80]:
!cat extremes.txt

# Temperature Extremes
34.00
9.00


In [ ]:
dates[]