 # Simple Arrays
 
 Let's load in NumPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.13.1'

## Native Python arrays

In [3]:
import array

In [4]:
# create an array with the integers 1 thru 10

number_list = list(range(11))
print(number_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [5]:
type(number_list)

list

In [6]:
an_array = array.array('i', number_list)
print(an_array)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [7]:
another_array = array.array('f', number_list)
print(another_array)

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])


## NumPy arrays

In [8]:
numpy_array = np.array(number_list)
print(numpy_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [10]:
numpy_array2 = np.array([1,2,3,4])
print(numpy_array2)

[1 2 3 4]


In [11]:
np.array([1.2,2.4,3.6])

array([ 1.2,  2.4,  3.6])

In [12]:
np.array([1.2,2.4,3.6, 5])

array([ 1.2,  2.4,  3.6,  5. ])

In [13]:
np.array(['hello', 'goodbye'])

array(['hello', 'goodbye'],
      dtype='<U7')

In [15]:
np.array([1,2.5,'hello', True])

array(['1', '2.5', 'hello', 'True'],
      dtype='<U32')

In [19]:
np.array([1.0,2.0,3.0,5.0], dtype='bool')

array([ True,  True,  True,  True], dtype=bool)

## Creating arrays (in better ways)

In [21]:
# arrays of zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.empty(10)

array([  6.92958165e-310,   1.07319833e-316,   6.92957677e-310,
         6.92957677e-310,   6.92957677e-310,   6.92957677e-310,
         6.92957677e-310,   6.92957677e-310,   6.92957677e-310,
         6.92957677e-310])

In [24]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [25]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [26]:
np.full((5,5), -99)

array([[-99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99]])

In [27]:
np.full((5,5), np.nan)

array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan]])

In [28]:
type(np.nan)

float

In [29]:
np.full((5,5), np.nan) + np.full((5,5), -99)

array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan]])

In [31]:
np.nan**1

nan

In [32]:
np.arange(start=0,stop=20,step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
np.linspace(0,20,10, endpoint=False)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.])

In [37]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [38]:
np.random.random(5)

array([ 0.63630061,  0.62214455,  0.57130694,  0.06580043,  0.17644201])

In [40]:
np.random.randint(0,10,(12,12))

array([[5, 5, 4, 1, 0, 4, 6, 0, 4, 6, 4, 6],
       [7, 6, 3, 2, 3, 5, 4, 1, 1, 3, 0, 9],
       [9, 3, 3, 8, 4, 9, 5, 5, 0, 0, 9, 9],
       [8, 7, 6, 6, 6, 4, 4, 7, 7, 0, 7, 9],
       [2, 1, 4, 2, 0, 3, 9, 1, 2, 2, 3, 0],
       [0, 6, 8, 6, 7, 8, 0, 5, 6, 9, 5, 9],
       [4, 0, 6, 0, 8, 3, 3, 0, 9, 6, 2, 3],
       [3, 4, 5, 4, 7, 7, 1, 1, 9, 2, 4, 8],
       [1, 6, 7, 3, 4, 8, 7, 1, 3, 3, 8, 2],
       [1, 4, 4, 1, 7, 3, 5, 0, 5, 7, 6, 3],
       [2, 0, 4, 4, 6, 5, 3, 0, 5, 9, 3, 6],
       [1, 0, 9, 6, 0, 4, 5, 9, 6, 4, 3, 7]])

In [42]:
np.random.normal(0,4,(3,3))

array([[ -4.56919351,   1.55747891,   2.92443492],
       [ -4.51725148,  -0.61890012, -10.67945885],
       [ -2.85244566,  -6.16336957,  -8.0206812 ]])

In [45]:
## solution

my_matrix = np.random.normal(5,3,(10,10))
#print(my_matrix)

In [46]:
np.array(my_matrix, dtype='int')

array([[ 6,  5,  6,  4,  2,  2,  6,  2,  5,  1],
       [ 2,  7,  3, 11,  1,  0,  5,  8, 10,  5],
       [10,  3,  6,  1,  0,  5,  6,  4,  0,  7],
       [ 3,  7,  6,  1,  6,  7,  3,  4,  8,  7],
       [ 9,  6,  6,  5,  3,  4,  8,  4,  0,  6],
       [ 2,  8,  1,  3,  6,  8,  5,  2,  5, 11],
       [ 4,  3,  4,  2,  0,  6,  7,  1, 10,  3],
       [ 0,  1,  7,  0,  2,  5,  2,  5,  3, -2],
       [-1,  4,  1,  5,  4,  6,  3,  3,  4,  0],
       [ 0,  7,  8,  6, 10,  8,  3,  3,  7,  9]])

In [48]:
np.array(np.array(my_matrix , dtype='int'), dtype='str')

array([['6', '5', '6', '4', '2', '2', '6', '2', '5', '1'],
       ['2', '7', '3', '11', '1', '0', '5', '8', '10', '5'],
       ['10', '3', '6', '1', '0', '5', '6', '4', '0', '7'],
       ['3', '7', '6', '1', '6', '7', '3', '4', '8', '7'],
       ['9', '6', '6', '5', '3', '4', '8', '4', '0', '6'],
       ['2', '8', '1', '3', '6', '8', '5', '2', '5', '11'],
       ['4', '3', '4', '2', '0', '6', '7', '1', '10', '3'],
       ['0', '1', '7', '0', '2', '5', '2', '5', '3', '-2'],
       ['-1', '4', '1', '5', '4', '6', '3', '3', '4', '0'],
       ['0', '7', '8', '6', '10', '8', '3', '3', '7', '9']],
      dtype='<U21')